import type { ComponentType, SVGProps } from "react";

import AlertCircleSource from "~icons/lucide/circle-alert";
import AlertTriangleSource from "~icons/lucide/triangle-alert";
import ClaudeSource from "~icons/logos/claude-icon";
import DefaultFileSource from "~icons/vscode-icons/default-file";
import FileTypeApacheSource from "~icons/vscode-icons/file-type-apache";
import FileTypeAudioSource from "~icons/vscode-icons/file-type-audio";
import FileTypeBinarySource from "~icons/vscode-icons/file-type-binary";
import FileTypeBunSource from "~icons/vscode-icons/file-type-bun";
import FileTypeCSource from "~icons/vscode-icons/file-type-c";
import FileTypeCargoSource from "~icons/vscode-icons/file-type-cargo";
import FileTypeCertSource from "~icons/vscode-icons/file-type-cert";
import FileTypeCmakeSource from "~icons/vscode-icons/file-type-cmake";
import FileTypeConfigSource from "~icons/vscode-icons/file-type-config";
import FileTypeCppSource from "~icons/vscode-icons/file-type-cpp";
import FileTypeCsharpSource from "~icons/vscode-icons/file-type-csharp";
import FileTypeCssSource from "~icons/vscode-icons/file-type-css";
import FileTypeDartSource from "~icons/vscode-icons/file-type-dartlang";
import FileTypeDbSource from "~icons/vscode-icons/file-type-db";
import FileTypeDockerSource from "~icons/vscode-icons/file-type-docker";
import FileTypeDotenvSource from "~icons/vscode-icons/file-type-dotenv";
import FileTypeEslintSource from "~icons/vscode-icons/file-type-eslint";
import FileTypeExcelSource from "~icons/vscode-icons/file-type-excel";
import FileTypeFontSource from "~icons/vscode-icons/file-type-font";
import FileTypeGeminiSource from "~icons/vscode-icons/file-type-gemini";
import FileTypeGitSource from "~icons/vscode-icons/file-type-git";
import FileTypeGoSource from "~icons/vscode-icons/file-type-go";
import FileTypeGoWorkSource from "~icons/vscode-icons/file-type-go-work";
import FileTypeGradleSource from "~icons/vscode-icons/file-type-gradle";
import FileTypeGraphqlSource from "~icons/vscode-icons/file-type-graphql";
import FileTypeHtmlSource from "~icons/vscode-icons/file-type-html";
import FileTypeImageSource from "~icons/vscode-icons/file-type-image";
import FileTypeIniSource from "~icons/vscode-icons/file-type-ini";
import FileTypeJavaSource from "~icons/vscode-icons/file-type-java";
import FileTypeJsSource from "~icons/vscode-icons/file-type-js";
import FileTypeJsConfigSource from "~icons/vscode-icons/file-type-jsconfig";
import FileTypeJsonSource from "~icons/vscode-icons/file-type-json";
import FileTypeKeySource from "~icons/vscode-icons/file-type-key";
import FileTypeKotlinSource from "~icons/vscode-icons/file-type-kotlin";
import FileTypeLicenseSource from "~icons/vscode-icons/file-type-license";
import FileTypeLogSource from "~icons/vscode-icons/file-type-log";
import FileTypeMarkdownSource from "~icons/vscode-icons/file-type-markdown";
import FileTypeMavenSource from "~icons/vscode-icons/file-type-maven";
import FileTypeNginxSource from "~icons/vscode-icons/file-type-nginx";
import FileTypeNodeSource from "~icons/vscode-icons/file-type-node";
import FileTypeNpmSource from "~icons/vscode-icons/file-type-npm";
import FileTypePackageSource from "~icons/vscode-icons/file-type-package";
import FileTypePdfSource from "~icons/vscode-icons/file-type-pdf2";
import FileTypePhpSource from "~icons/vscode-icons/file-type-php";
import FileTypePnpmSource from "~icons/vscode-icons/file-type-pnpm";
import FileTypePowerpointSource from "~icons/vscode-icons/file-type-powerpoint";
import FileTypePowershellSource from "~icons/vscode-icons/file-type-powershell";
import FileTypePrettierSource from "~icons/vscode-icons/file-type-prettier";
import FileTypePrismaSource from "~icons/vscode-icons/file-type-prisma";
import FileTypePythonSource from "~icons/vscode-icons/file-type-python";
import FileTypeReactJsSource from "~icons/vscode-icons/file-type-reactjs";
import FileTypeReactTsSource from "~icons/vscode-icons/file-type-reactts";
import FileTypeRubySource from "~icons/vscode-icons/file-type-ruby";
import FileTypeRustSource from "~icons/vscode-icons/file-type-rust";
import FileTypeScssSource from "~icons/vscode-icons/file-type-scss";
import FileTypeShellSource from "~icons/vscode-icons/file-type-shell";
import FileTypeSqlSource from "~icons/vscode-icons/file-type-sql";
import FileTypeSqliteSource from "~icons/vscode-icons/file-type-sqlite";
import FileTypeSvelteSource from "~icons/vscode-icons/file-type-svelte";
import FileTypeSwiftSource from "~icons/vscode-icons/file-type-swift";
import FileTypeSystemdSource from "~icons/vscode-icons/file-type-systemd";
import FileTypeTerraformSource from "~icons/vscode-icons/file-type-terraform";
import FileTypeTextSource from "~icons/vscode-icons/file-type-text";
import FileTypeTomlSource from "~icons/vscode-icons/file-type-toml";
import FileTypeTsConfigSource from "~icons/vscode-icons/file-type-tsconfig";
import FileTypeTsSource from "~icons/vscode-icons/file-type-typescript";
import FileTypeTsDefSource from "~icons/vscode-icons/file-type-typescriptdef";
import FileTypeVideoSource from "~icons/vscode-icons/file-type-video";
import FileTypeViteSource from "~icons/vscode-icons/file-type-vite";
import FileTypeVitestSource from "~icons/vscode-icons/file-type-vitest";
import FileTypeVueSource from "~icons/vscode-icons/file-type-vue";
import FileTypeWebpackSource from "~icons/vscode-icons/file-type-webpack";
import FileTypeWordSource from "~icons/vscode-icons/file-type-word";
import FileTypeXmlSource from "~icons/vscode-icons/file-type-xml";
import FileTypeYamlSource from "~icons/vscode-icons/file-type-yaml";
import FileTypeYarnSource from "~icons/vscode-icons/file-type-yarn";
import FileTypeZipSource from "~icons/vscode-icons/file-type-zip";
import ArrowLeftSource from "~icons/lucide/arrow-left";
import ArrowRightSource from "~icons/lucide/arrow-right";
import BanSource from "~icons/lucide/ban";
import BookOpenSource from "~icons/lucide/book-open";
import BotSource from "~icons/lucide/bot";
import BrainSource from "~icons/lucide/brain";
import BrushCleaningSource from "~icons/lucide/brush-cleaning";
import CheckSource from "~icons/lucide/check";
import CheckCircle2Source from "~icons/lucide/circle-check";
import ChevronDownSource from "~icons/lucide/chevron-down";
import ChevronRightSource from "~icons/lucide/chevron-right";
import ChevronUpSource from "~icons/lucide/chevron-up";
import CircleSource from "~icons/lucide/circle";
import Clock3Source from "~icons/lucide/clock-3";
import CloudSource from "~icons/lucide/cloud";
import ClipboardPasteSource from "~icons/lucide/clipboard-paste";
import CopySource from "~icons/lucide/copy";
import CpuSource from "~icons/lucide/cpu";
import DownloadSource from "~icons/lucide/download";
import Edit3Source from "~icons/lucide/pen-line";
import ExternalLinkSource from "~icons/lucide/external-link";
import EyeSource from "~icons/lucide/eye";
import EyeOffSource from "~icons/lucide/eye-off";
import FileSource from "~icons/lucide/file";
import FilePenLineSource from "~icons/lucide/file-pen-line";
import FileTextSource from "~icons/lucide/file-text";
import FolderSource from "~icons/lucide/folder";
import FolderOpenSource from "~icons/lucide/folder-open";
import FolderTreeSource from "~icons/lucide/folder-tree";
import GitBranchSource from "~icons/lucide/git-branch";
import GitCommitHorizontalSource from "~icons/lucide/git-commit-horizontal";
import GlobeSource from "~icons/lucide/globe";
import Globe2Source from "~icons/lucide/earth";
import GripVerticalSource from "~icons/lucide/grip-vertical";
import HardDriveSource from "~icons/lucide/hard-drive";
import HistorySource from "~icons/lucide/history";
import HomeSource from "~icons/lucide/house";
import ImageIconSource from "~icons/lucide/image";
import ImageOffSource from "~icons/lucide/image-off";
import KeySource from "~icons/lucide/key";
import LayoutGridSource from "~icons/lucide/layout-grid";
import Link2Source from "~icons/lucide/link-2";
import LightbulbSource from "~icons/lucide/lightbulb";
import ListSource from "~icons/lucide/list";
import Loader2Source from "~icons/lucide/loader-circle";
import LockSource from "~icons/lucide/lock";
import LogOutSource from "~icons/lucide/log-out";
import MessageSquareSource from "~icons/lucide/message-square";
import MessageSquareTextSource from "~icons/lucide/message-square-text";
import MonitorSmartphoneSource from "~icons/lucide/monitor-smartphone";
import MoonSource from "~icons/lucide/moon";
import MoreHorizontalSource from "~icons/lucide/ellipsis";
import OpenAISource from "~icons/logos/openai-icon";
import PanelLeftSource from "~icons/lucide/panel-left";
import PanelLeftCloseSource from "~icons/lucide/panel-left-close";
import PanelRightCloseSource from "~icons/lucide/panel-right-close";
import PanelRightOpenSource from "~icons/lucide/panel-right-open";
import PaperclipSource from "~icons/lucide/paperclip";
import PencilSource from "~icons/lucide/pencil";
import PinSource from "~icons/lucide/pin";
import PinOffSource from "~icons/lucide/pin-off";
import PlaySource from "~icons/lucide/play";
import PlugSource from "~icons/lucide/plug";
import PlusSource from "~icons/lucide/plus";
import RadioSource from "~icons/lucide/radio";
import Redo2Source from "~icons/lucide/redo-2";
import RefreshCwSource from "~icons/lucide/refresh-cw";
import ReplaceSource from "~icons/lucide/replace";
import SaveSource from "~icons/lucide/save";
import ScrollTextSource from "~icons/lucide/scroll-text";
import ScissorsSource from "~icons/lucide/scissors";
import SearchSource from "~icons/lucide/search";
import SendSource from "~icons/lucide/send";
import ServerSource from "~icons/lucide/server";
import SettingsSource from "~icons/lucide/settings";
import Settings2Source from "~icons/lucide/settings-2";
import Share2Source from "~icons/lucide/share-2";
import ShieldSource from "~icons/lucide/shield";
import SparklesSource from "~icons/lucide/sparkles";
import SquareSource from "~icons/lucide/square";
import SquarePenSource from "~icons/lucide/square-pen";
import SunSource from "~icons/lucide/sun";
import TagSource from "~icons/lucide/tag";
import TargetSource from "~icons/lucide/crosshair";
import TerminalSource from "~icons/lucide/terminal";
import TimerSource from "~icons/lucide/timer";
import TextSelectSource from "~icons/lucide/text-select";
import Trash2Source from "~icons/lucide/trash-2";
import Undo2Source from "~icons/lucide/undo-2";
import UploadSource from "~icons/lucide/upload";
import UserSource from "~icons/lucide/user";
import WifiSource from "~icons/lucide/wifi";
import WifiOffSource from "~icons/lucide/wifi-off";
import WrenchSource from "~icons/lucide/wrench";
import XSource from "~icons/lucide/x";
import XCircleSource from "~icons/lucide/circle-x";
import ZapSource from "~icons/lucide/zap";
import fileIconSvgSource from "~icons/lucide/file?raw";
import folderIconSvgSource from "~icons/lucide/folder?raw";

type IconSource = ComponentType<SVGProps<SVGSVGElement> & { title?: string }>;

type IconProps = SVGProps<SVGSVGElement> & {
  absoluteStrokeWidth?: boolean;
  size?: number | string;
  title?: string;
};

export type IconComponent = ComponentType<IconProps>;

function createIcon(Source: IconSource): IconComponent {
  return function Icon({
    absoluteStrokeWidth: _absoluteStrokeWidth,
    height,
    size,
    width,
    ...props
  }) {
    const nextProps: IconProps = { ...props };
    if (size !== undefined) {
      nextProps.width = width ?? size;
      nextProps.height = height ?? size;
    } else {
      if (width !== undefined) nextProps.width = width;
      if (height !== undefined) nextProps.height = height;
    }
    return <Source {...nextProps} />;
  };
}

export const AlertCircle = createIcon(AlertCircleSource);
export const AlertTriangle = createIcon(AlertTriangleSource);
export const ClaudeIcon = createIcon(ClaudeSource);
export const FileTypeGeminiIcon = createIcon(FileTypeGeminiSource);
export const DefaultFile = createIcon(DefaultFileSource);
export const FileTypeApache = createIcon(FileTypeApacheSource);
export const FileTypeAudio = createIcon(FileTypeAudioSource);
export const FileTypeBinary = createIcon(FileTypeBinarySource);
export const FileTypeBun = createIcon(FileTypeBunSource);
export const FileTypeC = createIcon(FileTypeCSource);
export const FileTypeCargo = createIcon(FileTypeCargoSource);
export const FileTypeCert = createIcon(FileTypeCertSource);
export const FileTypeCmake = createIcon(FileTypeCmakeSource);
export const FileTypeConfig = createIcon(FileTypeConfigSource);
export const FileTypeCpp = createIcon(FileTypeCppSource);
export const FileTypeCsharp = createIcon(FileTypeCsharpSource);
export const FileTypeCss = createIcon(FileTypeCssSource);
export const FileTypeDart = createIcon(FileTypeDartSource);
export const FileTypeDb = createIcon(FileTypeDbSource);
export const FileTypeDocker = createIcon(FileTypeDockerSource);
export const FileTypeDotenv = createIcon(FileTypeDotenvSource);
export const FileTypeEslint = createIcon(FileTypeEslintSource);
export const FileTypeExcel = createIcon(FileTypeExcelSource);
export const FileTypeFont = createIcon(FileTypeFontSource);
export const FileTypeGit = createIcon(FileTypeGitSource);
export const FileTypeGo = createIcon(FileTypeGoSource);
export const FileTypeGoWork = createIcon(FileTypeGoWorkSource);
export const FileTypeGradle = createIcon(FileTypeGradleSource);
export const FileTypeGraphql = createIcon(FileTypeGraphqlSource);
export const FileTypeHtml = createIcon(FileTypeHtmlSource);
export const FileTypeImage = createIcon(FileTypeImageSource);
export const FileTypeIni = createIcon(FileTypeIniSource);
export const FileTypeJava = createIcon(FileTypeJavaSource);
export const FileTypeJs = createIcon(FileTypeJsSource);
export const FileTypeJsConfig = createIcon(FileTypeJsConfigSource);
export const FileTypeJson = createIcon(FileTypeJsonSource);
export const FileTypeKey = createIcon(FileTypeKeySource);
export const FileTypeKotlin = createIcon(FileTypeKotlinSource);
export const FileTypeLicense = createIcon(FileTypeLicenseSource);
export const FileTypeLog = createIcon(FileTypeLogSource);
export const FileTypeMarkdown = createIcon(FileTypeMarkdownSource);
export const FileTypeMaven = createIcon(FileTypeMavenSource);
export const FileTypeNginx = createIcon(FileTypeNginxSource);
export const FileTypeNode = createIcon(FileTypeNodeSource);
export const FileTypeNpm = createIcon(FileTypeNpmSource);
export const FileTypePackage = createIcon(FileTypePackageSource);
export const FileTypePdf = createIcon(FileTypePdfSource);
export const FileTypePhp = createIcon(FileTypePhpSource);
export const FileTypePnpm = createIcon(FileTypePnpmSource);
export const FileTypePowerpoint = createIcon(FileTypePowerpointSource);
export const FileTypePowershell = createIcon(FileTypePowershellSource);
export const FileTypePrettier = createIcon(FileTypePrettierSource);
export const FileTypePrisma = createIcon(FileTypePrismaSource);
export const FileTypePython = createIcon(FileTypePythonSource);
export const FileTypeReactJs = createIcon(FileTypeReactJsSource);
export const FileTypeReactTs = createIcon(FileTypeReactTsSource);
export const FileTypeRuby = createIcon(FileTypeRubySource);
export const FileTypeRust = createIcon(FileTypeRustSource);
export const FileTypeScss = createIcon(FileTypeScssSource);
export const FileTypeShell = createIcon(FileTypeShellSource);
export const FileTypeSql = createIcon(FileTypeSqlSource);
export const FileTypeSqlite = createIcon(FileTypeSqliteSource);
export const FileTypeSvelte = createIcon(FileTypeSvelteSource);
export const FileTypeSwift = createIcon(FileTypeSwiftSource);
export const FileTypeSystemd = createIcon(FileTypeSystemdSource);
export const FileTypeTerraform = createIcon(FileTypeTerraformSource);
export const FileTypeText = createIcon(FileTypeTextSource);
export const FileTypeToml = createIcon(FileTypeTomlSource);
export const FileTypeTs = createIcon(FileTypeTsSource);
export const FileTypeTsConfig = createIcon(FileTypeTsConfigSource);
export const FileTypeTsDef = createIcon(FileTypeTsDefSource);
export const FileTypeVideo = createIcon(FileTypeVideoSource);
export const FileTypeVite = createIcon(FileTypeViteSource);
export const FileTypeVitest = createIcon(FileTypeVitestSource);
export const FileTypeVue = createIcon(FileTypeVueSource);
export const FileTypeWebpack = createIcon(FileTypeWebpackSource);
export const FileTypeWord = createIcon(FileTypeWordSource);
export const FileTypeXml = createIcon(FileTypeXmlSource);
export const FileTypeYaml = createIcon(FileTypeYamlSource);
export const FileTypeYarn = createIcon(FileTypeYarnSource);
export const FileTypeZip = createIcon(FileTypeZipSource);
export const ArrowLeft = createIcon(ArrowLeftSource);
export const ArrowRight = createIcon(ArrowRightSource);
export const Ban = createIcon(BanSource);
export const BookOpen = createIcon(BookOpenSource);
export const Bot = createIcon(BotSource);
export const Brain = createIcon(BrainSource);
export const BrushCleaning = createIcon(BrushCleaningSource);
export const Check = createIcon(CheckSource);
export const CheckCircle2 = createIcon(CheckCircle2Source);
export const ChevronDown = createIcon(ChevronDownSource);
export const ChevronRight = createIcon(ChevronRightSource);
export const ChevronUp = createIcon(ChevronUpSource);
export const Circle = createIcon(CircleSource);
export const ClipboardPaste = createIcon(ClipboardPasteSource);
export const Clock3 = createIcon(Clock3Source);
export const Cloud = createIcon(CloudSource);
export const Copy = createIcon(CopySource);
export const Cpu = createIcon(CpuSource);
export const Download = createIcon(DownloadSource);
export const Edit3 = createIcon(Edit3Source);
export const ExternalLink = createIcon(ExternalLinkSource);
export const Eye = createIcon(EyeSource);
export const EyeOff = createIcon(EyeOffSource);
export const File = createIcon(FileSource);
export const FilePenLine = createIcon(FilePenLineSource);
export const FileText = createIcon(FileTextSource);
export const Folder = createIcon(FolderSource);
export const FolderOpen = createIcon(FolderOpenSource);
export const FolderTree = createIcon(FolderTreeSource);
export const GitBranch = createIcon(GitBranchSource);
export const GitCommitHorizontal = createIcon(GitCommitHorizontalSource);
export const Globe = createIcon(GlobeSource);
export const Globe2 = createIcon(Globe2Source);
export const GripVertical = createIcon(GripVerticalSource);
export const HardDrive = createIcon(HardDriveSource);
export const History = createIcon(HistorySource);
export const Home = createIcon(HomeSource);
export const ImageIcon = createIcon(ImageIconSource);
export const ImageOff = createIcon(ImageOffSource);
export const Key = createIcon(KeySource);
export const LayoutGrid = createIcon(LayoutGridSource);
export const Link2 = createIcon(Link2Source);
export const Lightbulb = createIcon(LightbulbSource);
export const List = createIcon(ListSource);
export const Loader2 = createIcon(Loader2Source);
export const Lock = createIcon(LockSource);
export const LogOut = createIcon(LogOutSource);
export const MessageSquare = createIcon(MessageSquareSource);
export const MessageSquareText = createIcon(MessageSquareTextSource);
export const MonitorSmartphone = createIcon(MonitorSmartphoneSource);
export const Moon = createIcon(MoonSource);
export const MoreHorizontal = createIcon(MoreHorizontalSource);
export const OpenaiChatgptIcon = createIcon(OpenAISource);
export const PanelLeft = createIcon(PanelLeftSource);
export const PanelLeftClose = createIcon(PanelLeftCloseSource);
export const PanelRightClose = createIcon(PanelRightCloseSource);
export const PanelRightOpen = createIcon(PanelRightOpenSource);
export const Paperclip = createIcon(PaperclipSource);
export const Pencil = createIcon(PencilSource);
export const Pin = createIcon(PinSource);
export const PinOff = createIcon(PinOffSource);
export const Play = createIcon(PlaySource);
export const Plug = createIcon(PlugSource);
export const Plus = createIcon(PlusSource);
export const Radio = createIcon(RadioSource);
export const Redo2 = createIcon(Redo2Source);
export const RefreshCw = createIcon(RefreshCwSource);
export const Replace = createIcon(ReplaceSource);
export const Save = createIcon(SaveSource);
export const ScrollText = createIcon(ScrollTextSource);
export const Scissors = createIcon(ScissorsSource);
export const Search = createIcon(SearchSource);
export const Send = createIcon(SendSource);
export const Server = createIcon(ServerSource);
export const Settings = createIcon(SettingsSource);
export const Settings2 = createIcon(Settings2Source);
export const Share2 = createIcon(Share2Source);
export const Shield = createIcon(ShieldSource);
export const Sparkles = createIcon(SparklesSource);
export const Square = createIcon(SquareSource);
export const SquarePen = createIcon(SquarePenSource);
export const Sun = createIcon(SunSource);
export const Tag = createIcon(TagSource);
export const Target = createIcon(TargetSource);
export const Terminal = createIcon(TerminalSource);
export const Timer = createIcon(TimerSource);
export const TextSelect = createIcon(TextSelectSource);
export const Trash2 = createIcon(Trash2Source);
export const Undo2 = createIcon(Undo2Source);
export const Upload = createIcon(UploadSource);
export const User = createIcon(UserSource);
export const Wifi = createIcon(WifiSource);
export const WifiOff = createIcon(WifiOffSource);
export const Wrench = createIcon(WrenchSource);
export const X = createIcon(XSource);
export const XCircle = createIcon(XCircleSource);
export const Zap = createIcon(ZapSource);
const fileIconSvg = fileIconSvgSource as unknown as string;
const folderIconSvg = folderIconSvgSource as unknown as string;
export { fileIconSvg, folderIconSvg };
